# set up smalltalk ci and try to build the baseline
on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.appveyor.yml'
      - '.travis.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.appveyor.yml'
      - '.travis.yml'
jobs:
  build:
    strategy:
      matrix:
        smalltalk: [  Pharo64-8.0 ]
        os: [ ubuntu-18.04 ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
